import "./WorkerForm.css";

export const metadata = {
  title: "Работа с формой",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div> {children} </div>;
}
