import "./globals.css";
import Header from "./components/Header";
import { inter } from './ui/fonts';

export const metadata = {
  title: "Smeto тестовый проект",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
    <html lang="en">
      <body className={inter.className}>
        <Header/>
       <div className="smetoStyle"> {children} </div>
      </body>
    </html>
  );
}
//<body className={`${geistSans.variable} ${geistMono.variable}`}></body>