import "./style.css";


export const metadata = {
  title: "Hello Show!!!",
  //description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>TOP info</h1>
        {children}
      </body>
    </html>
  );
}
